tdm-project/tdm-polystore

Makefile, docker/Dockerfile.tiledb, docker/docker-compose.yml-tmpl, notebooks/data_store.ipynb
and updated to the new tiledb python API.
=> updated to new crs4/hadoop image

.travis.yml, .travis/docker-compose.yml, .travis/run_checks, scripts/here/HERE_JSON_extractor.py, setup.py, tdmq/__init__.py, tdmq/api.py, tdmq/db.py, tdmq/utils.py, tests/test_api.py, tests/test_cli.py
Adds a minimal CI setup for running existing tests.
=> Run unit tests

.travis/run_checks, notebooks/TDMQ_API_Experiments.ipynb, tdmq/api.py, tdmq/db.py, tdmq/query_builder.py, tests/data/sensor_types.json, tests/data/sensors.json, tests/test_api.py, tests/test_db_query.py
Adds `sensor_type` filtering by any attribute and `sensor` filtering by type.
=> Filter sensor types

.travis.yml, .travis/run_checks, apidocs/Makefile, apidocs/api.rst, apidocs/conf.py, apidocs/index.rst, docker/Dockerfile.web, tdmq/api.py, tdmq/db.py
Adds the Sphinx setup for building the API docs. Also updates the docs themselves.
=> Build API docs

notebooks/TDMQ_API_Experiments.ipynb, tdmq/api.py, tdmq/db.py, tdmq/query_builder.py, tests/data/sensors.json, tests/test_db.py, tests/test_db_query.py
This PR adds the ability to filter sensors by generic attributes in the description field. Currently filtering by footprint, type and attributes are mutually exclusive.
=> Filter sensors

notebooks/ngsi2polystore.ipynb
This PR adds an example of how to populate db from a ngsi message.
=> Ngsi2polystore

tdmq/db.py, tests/test_cli.py, tests/test_db.py
If db already exists it is not dropped & recreated (all data will be lost). Flag '--drop' allows to force recreation.
=> init db idempotency

examples/docker/Dockerfile.dpc, examples/docker/build.sh, examples/docker/docker-compose.yml, examples/dpc/clientplus.py, examples/dpc/ingestor.py
this PR improves the dpc examples, adding command line parameters handling, a docker image and a docke-compose file
=> Ingestor improvements

tdmq/api.py, tdmq/client/client.py, tdmq/client/sources.py, tdmq/db.py, tests/client/test_non_scalar_source.py, tests/client/test_source.py, tests/test_db.py
This PR simplifies the Client through two main changes:
* remove "management" of Source objects
* simplify the source factory concept to a simple rule:
```
len(shape) > 0 => NonScalar
else => Scalar
```
Let's discuss.
=> Simplify client

examples/here/ingestor.py, examples/here/ingestor_driver.sh, notebooks/here_traffic.ipynb
Fixes #40
Updates the traffic data example to the latest API, and adds `app_id` and `app_code` to the ingestor driver.
=> Update traffic example

Makefile
Updates `DOCKER_STACKS_REV` in `Makefile`.
=> Update docker-stacks revision

Makefile
Update jupyter hub DOCKER_STACKS revision
=> Update version of jupyter hub stack release

docker/Dockerfile.web, docker/docker-compose.yml-tmpl, docker/prometheus.yml, docker/web-entrypoint.sh, setup.py, tdmq/api.py, tdmq/app.py, tdmq/client/client.py, tdmq/wsgi.py, tests/conftest.py, tests/test_api.py, tests/test_factory.py
This PR adds some initial Prometheus metrics to monitor REST API requests for tdmq. In particular it sends request duration in seconds and response size in bytes
=> Add prometheus instrumentation

tdmq/api-spec.yaml, tdmq/api.py
Moves the API documentation from the `tdmq/api.py` file to the API specification.
=> Add spec docs

Makefile, docker/Dockerfile.jupyter
Changes docker hub image to include notebooks in TDMQ_DIST directory
=> Changes docker hub image to include notebooks in TDMQ_DIST directory

tdmq/api-spec.yaml, tdmq/api.py, tdmq/model.py, tests/client/test_source.py, tests/test_api.py
* Fix missing required attributes in anonymized response
* Introduce `anonymized` and `only_public` API parameters
=> Reverts to only returning public sources by default

tdmq/utils.py, tests/test_api.py
=> Allow whitespace in ROI scanning

docker/Dockerfile.tdmq-client-conda, tdmq/api.py, tdmq/app.py, tdmq/db.py, tdmq/requirements-server.txt
This PR adds configuration of tdmq logging and adds logging of requests.  In addition, it also adds recreation of the DB connection if it's closed for whatever reason.  This last change should fix issue #84
=> Configure logging; log requests

tdmq/api-spec.yaml, tdmq/api.py, tdmq/client/client.py, tdmq/client/sources.py, tdmq/db.py, tdmq/model.py, tests/client/test_timeseries.py, tests/test_api.py
New client call, with supporting API call, to get most recent records in a timeseries
=> New call get_latest_activities

.github/workflows/main.yml, Makefile, docker/Dockerfile.jupyter, docker/Dockerfile.tdmq-client-conda, docker/docker-compose.hdfs.yml, docker/docker-compose.testing.yml-tmpl, examples/here/ingestor.py, scripts/make_zones_db.py, tdmq/api.py, tdmq/app.py, tdmq/client/__init__.py, tdmq/client/client.py, tdmq/client/sources.py, tdmq/client/timeseries.py, tdmq/db.py, tdmq/errors.py, tdmq/loc_anonymizer.py, tdmq/model.py, tdmq/wsgi.py, tests/client/test_client.py, tests/client/test_non_scalar_source.py, tests/client/test_records.py, tests/client/test_source.py, tests/client/test_timeseries.py, tests/conftest.py, tests/test_api.py, tests/test_cli.py, tests/test_db.py, tests/test_factory.py, tests/test_loc_anonymizer.py
ports the CI workflow from Travis to GH Actions.  Includes, build, test and push to dockerhub.  Only tests not involving HDFS are run.
=> Github workflow

.github/workflows/main.yml
Add pushing images to CRS4's docker image repository to the main github workflow.
=> Enable pushing images to CRS4's docker image repository

tdmq/api-spec.yaml, tdmq/api.py, tdmq/client/client.py, tests/test_api.py
New /timeseries API moved to /timeseries_stream
=> Restore old /timeseries API for backwards compatibility.

tdmq/db.py, tdmq/errors.py, tests/test_api.py
Fix some old exception names forgotten during refactoring PR #118
=> Fix bad exception class names

tdmq/api.py, tdmq/db.py, tdmq/errors.py, tdmq/model.py, tests/test_api.py
The PR also makes some changes to the way the resulting exceptions are logged to try to make the logs less noisy.
=> Validate presence of values in POSTed ts records

scripts/make_zones_db.py
Fixes zone DB script to map geometries to EPSG:4326
=> Fix make_zones_db script
