notebooks/ExtractTrafficData.ipynb
scripts/here/HERE_JSON_extractor.py

Changes the script that gets the data from the original downloads to store a separate traffic info item for each timestamp (to avoid generating a huge file). Adds a notebook with an example on how to read the data produced by the script.

Traffic data processing example

---

docker/Dockerfile.tdmqc

this PR adds the installation of the python module requests in tdmqc docker image. This is a temporary fix, the dependency should be set in setup.py, which should be refactored in order to install individually the server or the client.

adds requests dependency in tdmqc docker image

---

Makefile
docker/Dockerfile.jupyter
docker/Dockerfile.tdmqc
docker/Dockerfile.web
docker/docker-compose.yml-tmpl

This PR tries to speed-up image rebuilds for this repository.
It brings code from the project closer to the last layers of the images, which reduces the number of layers that are rebuilt when code changes.  This is in part done by creating a `tdmqc-deps` image, which is then used by both the jupyter and the tdmqc image.  It's also done by pre-installing known dependencies (e.g., for the `web` image) so that when the real installation phase is run it finds that packages are already present.
Finally, more of the dependencies between things are described in the Makefile so that `make` can eliminate steps when possible.  Also, this brought me to write individual rules for each image so that now you can, for instance, rebuild the `web` image with `make web`.

Speed-up partial rebuilds

---

Makefile
docker/Dockerfile.web
docker/docker-compose.yml-tmpl
docker/web-entrypoint.sh

Start docker-compose with `make startdev` instead of `make start`.  Flask will be started in development mode.  Among other things, auto-reload is enabled and your local `tdmq` directory will be mounted in the container.  This means that any local change to the code will be almost immediately be picked up by the running web service.

New docker-compose development mode for flask app

---

tdmq/api.py
tdmq/app.py
tests/test_api.py

When a REST client tries to create a source performing a POST, and the source already exists the server returns 512. 
I think "409 - Conflict" should be more appropriate. 
https://www.restapitutorial.com/httpstatuscodes.html states that 409 is used when 
> The request could not be completed due to a conflict with the current state of the resource. This code is only allowed in situations where it is expected that the user might be able to resolve the conflict and resubmit the request
I think it applies to our case, since the state of the resource is "Already existent". I changed the response also to return  a json that explain the problem

Changes response code when the client tries to create a source already created

---

tdmq/api.py
tdmq/app.py
tdmq/wsgi.py
tests/conftest.py
tests/test_api.py

This PR builds on the PR #53 to refactor the definition of API routes as a Flask blueprint and parameterize the application prefix (e.g., `/api/v0.0`).  It also updates the version of pytest used by the project.

Refactor routes

---

tdmq/app.py
tdmq/client/client.py
tests/client/test_client.py

Remove trailing slashes from tdmq service URL provided to Client and from app prefix in tdmq configuration file.

Remove trailing slashes from tdmq url/prefix

---

tdmq/api.py
tests/test_api.py

`/service_info` was accidentally reusing part of the configuration object to form its response and modifying it in place, altering the configuration returned to subsequent calls.  This PR introduces a test to detect this problem and fixes the issue.

Fix accidental modification of config object

---

tdmq/app.py
tdmq/db.py
tdmq/db_manager.py
tests/conftest.py

This PR causes the DB connection to be cached in a module variable and be reused for all requests.  Previously the DB connection was reused only for each single request.

Reuse DB connection for multiple requests

---

tdmq/client/client.py
tdmq/client/sources.py
tdmq/client/timeseries.py
tests/client/test_non_scalar_source.py

Seeing that opening tiledb arrays can be relatively time-consuming, this (backwards-compatible) change to the client opens the array on the first use and keeps it open until it is explicitly closed (through `NonScalarSource.close_array`) or the source is garbage-collected.
**This change does mean that array insertions won't be flushed to disk immediately.**
For finer control on array lifetime, the PR also introduces a context manager which can be used as in:
source = client.get_source("id")
with source.array_context('w'):
source.ingest(...)
source.ingest(...)
source.ingest(...)

Keep tiledb arrays open for multiple accesses

---

tdmq/api-spec.yaml
tdmq/client/client.py
tdmq/client/sources.py
tests/client/test_client.py
tests/client/test_source.py

This PR exposes the `anonymized` API parameter in Client.get_source.  It also updates the API spec to reflect the fact that the two `GET /source/` API calls have been returning identical structures for a while, and it updates the client to take advantage of this by not doing a GET for every source in `Client.find_sources`.

Expose `anonymized` parameter in Client.get_source

---

tdmq/client/sources.py
tdmq/db.py
tdmq/model.py
tests/client/test_source.py
tests/data/sources.json

Refactor the client `Source` class to explicitly define the attributes that should be defined and accessible.  This also shields all client code from the structure returned by the API, making it easier for us to change that in the future should be decide to review some old decisions.
Finally, the PR adds the new Source metadata attributes providing source, station, and sensor ids.

Refactor client attributes and add new edge/station/sensor ids

---

tdmq/api-spec.yaml
tdmq/client/sources.py
tdmq/model.py
tests/client/test_client.py
tests/client/test_source.py
tests/test_api.py

Small refactoring of source search and api-spec, plus the addition of tests on search for sources matching new scalar sensor attributes (i.e., `edge_id`, `station_id`, etc.)

Refactor search params

---

tdmq/app.py
tdmq/client/client.py
tdmq/client/sources.py
tdmq/requirements-client.txt
tdmq/utils.py
tests/client/test_non_scalar_source.py
tests/conftest.py

This PR adds parameters to the Client, in a backwards compatible way, to expose the configuration of tiledb array extent sizes and some aspects of the array schema: specifically, attribute data type and filter list.  The interface is set up to easily support additional attribute properties.
The PR also changes the calculation of the default extent sizes as to generate defaults that empirically seem to work better.

Expose tiledb extent size and attribute properties

---

tdmq/client/client.py
tdmq/client/sources.py
tdmq/client/timeseries.py
tests/client/test_non_scalar_source.py
tests/client/test_records.py
tests/client/test_source.py
tests/client/test_timeseries.py

The polystore stores all timestamps in UTC.  This PR fixes the client to:
* consider timezone information provided in ingested timestamps;
* include timezone in all returned timestamps.
The current client implementation ignores the user-provided timezone, if any.  This means that a `datetime` created in local Rome time will erroneously be saved as its face value instead of being shifted to UTC.

handle timezones in timestamps

---

tdmq/client/__init__.py
tests/client/test_client.py

This PR simply imports the `Source` and `TimeSeries` into the `tdmq.client` module, making it easier to import them into client code.

Import `Source` and `TimeSeries` into `tdmq.client`

---

docker/Dockerfile.tdmq-db

Explained in the tsdb docs:  https://docs.timescale.com/v1.7/update-timescaledb/update-docker
Verified upgrade procedure for existing databases:
1. shut down the running container;
2. start a stock timescaledb-postgis:1.7.4-pg11 image mounting the existing database's volume;
3. `exec` into the container with `/bin/bash`;
4. open `psql` with the `-X` option;
5. **first thing in the session**:  run the command `ALTER EXTENSION timescaledb UPDATE;`
6. repeat the `ALTER...` command for all the databases in the pgsql cluster.

Update timescaledb to 1.7.4

---

tdmq/client/sources.py
tdmq/client/timeseries.py
tests/client/test_timeseries.py
tests/test_api.py

Adds `properties` argument to `Source.timeseries` to allow fetching only a subset of the full set of a source's controlled properties.

Expose the ability in client to query timeseries only for specific fields

---

tdmq/client/sources.py

Upon further discussion, we have decided to define for all Source objects the extra metadata properties for which access was added to `NonScalarSource` in PR #110.  Thus, this PR moves the definition of the properties from `NonScalarSource` to `Source`.

Define extra properties for root Source class

---

tdmq/api.py
tdmq/model.py
tests/test_api.py

Searching for sources by safe attributes (e.g., station_model=airRohr)
would automatically wrongly exclude all private sources.  This commit
fixes the problem and adds a test for it.

Fix: allow including private sources on safe attribute value searches

---

docker/web-entrypoint.sh
tdmq/api.py
tdmq/db.py
tdmq/gunicorn.conf.py

The previous default batch size (10000 records) results in timeouts.  Tested various batch sizes (1000, 2000, 3000, 5000).  Two-three thousand seems to be the sweet spot: smaller is slower overall; larger doesn't gain anything.

Lower default batch size to 2500 records

---

tdmq/tdmq_db_migrations/versions/cc88f3768771_apply_reorder_policy_on_record_table.py

This change should result in increased performance of queries extracting longer timeseries for a source.

Set reorder policy on the record table to match (source_id, time) index

---

tdmq/client/client.py
tests/client/test_client.py

The change in function signature is backwards compatible.

Add kwargs parameters to Client.find_sources

---

docker/Dockerfile.tdmq-db

The bitnami postgresql chart mounts the DB configuration in a file that the timescaledb image does not load.  This PR adds some code to our custom entrypoint to add an `include_dir` statement to the PgSQL configuration to load the extra DB configuration, if it exists.

Change tdmq-db entrypoint to include extra DB configuration

---

Makefile
docker/docker-compose.base.yml
docker/prometheus.yml
docker/tdmqc_run_tests
docker/web-entrypoint.sh
tdmq/app.py
tdmq/gunicorn.conf.py
tdmq/wsgi.py
tests/conftest.py
tests/test_api.py
tests/test_factory.py

Allowing multiple workers required modifying how the application exports
metrics for prometheus.  With this commit, they are exported from a
dedicated web app started by gunicorn, by default on port 9100.

Configure application to run with multiple gunicorn workers.

---

tdmq/api.py
tdmq/app.py
tdmq/client/client.py
tdmq/errors.py
tests/client/test_client.py
tests/client/test_non_scalar_source.py
tests/client/test_records.py
tests/client/test_source.py
tests/client/test_timeseries.py
tests/conftest.py
tests/test_api.py

This PR changes the client configuration served by tdmq depending on whether the client's request originates from inside or outside the internal network.

Support access from outside k8s cluster
